from pathlib import Path
from html import escape as E
root=Path('public/foca-foca')
# Transcribed from the six restaurant menu screenshots supplied in this conversation.
dishes=[
('mortadella','Mortadella',11,'classics','Mortadella com pistáchio, burrata, raspas de limão.','Mortadella with pistachio, burrata and lemon zest.'),
('golosa','Golosa',10,'classics','Hummus caseiro, pimentos assados, rúcula e parmesão.','Homemade hummus, roasted peppers, rocket and Parmesan.'),
('la-parmigiana','La Parmigiana',9.5,'classics','Beringela assada, tomate confitado, parmesão e orégão.','Roasted aubergine, confit tomato, Parmesan and oregano.'),
('del-giorno','Del Giorno',10,'classics','Fiambre italiano, rúcula, mozzarella fiordilatte.','Italian cooked ham, rocket and fior di latte mozzarella.'),
('napoli','Napoli',13,'signature','Salame Napoli, creme de gorgonzola e mascarpone, peras caramelizadas.','Napoli salami, gorgonzola and mascarpone cream, caramelised pears.'),
('messico-nuvole','Messico & Nuvole',13,'signature','Spianata picante, rúcula, beringela, parmesão e creme de pimentos.','Spicy spianata salami, rocket, aubergine, Parmesan and pepper cream.'),
('caprese','Caprese 2.0',12,'signature','Mozzarella de búfala, tomate, parmesão DOP, pesto de manjericão.','Buffalo mozzarella, tomato, Parmesan DOP and basil pesto.'),
('sole-calabria','Sole di Calabria',13,'signature',"’Nduja Spilinga, burrata, tomate confitado.","’Nduja from Spilinga, burrata and confit tomato."),
('la-tonnata','La Tonnata',13.5,'selection','Vitelo cozinhado lentamente, molho tonnato, agrião e pimenta preta.','Slow-cooked veal, tonnato sauce, watercress and black pepper.'),
('carciofara','Carciofara',13.5,'selection','Fiambre italiano, alcachofras grelhadas, pecorino romano, agrião e pimenta preta.','Italian cooked ham, grilled artichokes, Pecorino Romano, watercress and black pepper.'),
('crudo-bufala','Crudo & Búfala',13.5,'selection','Presunto italiano, mozzarella de búfala, rúcula.','Italian prosciutto, buffalo mozzarella and rocket.'),
('parma','Parma',13.5,'selection','Presunto italiano, burrata cremosa, tomate.','Italian prosciutto, creamy burrata and tomato.')]
extras=[
('Sobremesas e pastelaria','Desserts & pastries',[
('Cornetto simples','Plain cornetto',3,'',''),('Cornetto recheado','Filled cornetto',4.5,'Fiambre e queijo, creme de pistáchio, creme pasteleiro, Nutella ou creme de ricotta.','Ham and cheese, pistachio cream, custard, Nutella or ricotta cream.'),('Sfogliatella napolitana','Neapolitan sfogliatella',4,'',''),('Cannolo siciliano (2 un.)','Sicilian cannolo (2 pieces)',4,'',''),('Gelados italianos','Italian ice cream',4.5,'',''),('Fatia de torta','Slice of cake',4,'',''),('Babà napolitano','Neapolitan babà',5,'','')]),
('Cafetaria','Coffee & tea',[
('Café','Espresso',1.2,'',''),('Cappuccino','Cappuccino',3,'',''),('Cappuccino com leite vegetal','Cappuccino with plant-based milk',4,'',''),('Cappuccino com pistáchio','Pistachio cappuccino',4.5,'',''),('Galão / meia de leite','Galão / coffee with milk',2.5,'',''),('Chá','Tea',2,'','')]),
('Bebidas','Soft drinks',[
('Água Serra da Estrela · 0,5 L','Serra da Estrela still water · 0.5 L',2,'',''),('Água com gás Ferrarelle · 0,5 L','Ferrarelle sparkling water · 0.5 L',3,'',''),('Refrigerantes','Soft drinks',2.5,'Pepsi, Pepsi Zero, Lipton.','Pepsi, Pepsi Zero, Lipton.'),('Limonada','Lemonade',4,'',''),('Sumo de laranja','Orange juice',4,'','')]),
('Spritz','Spritz',[
('Aperol Spritz','Aperol Spritz',8,'Leve e cítrico. O sabor do verão italiano.','Light and citrusy. A taste of Italian summer.'),('Mirto Spritz','Mirto Spritz',8,'Os frutos da Sardenha. Herbal e aromático.','The fruits of Sardinia. Herbal and aromatic.'),('Campari Spritz','Campari Spritz',8,'Elegante, amargo e intenso.','Elegant, bitter and intense.'),('Limoncello Spritz','Limoncello Spritz',8,'Doce e cítrico. A frescura do sul de Itália.','Sweet and citrusy. The freshness of southern Italy.'),('Hugo Spritz','Hugo Spritz',8,'Floral. Inspirado pela frescura dos Alpes.','Floral. Inspired by the freshness of the Alps.')]),
('Cerveja','Beer',[
('Estrella Damm Imperial','Estrella Damm Imperial',3,'',''),('Free Damm · 0,0% álcool','Free Damm · 0.0% alcohol',3,'','')])]
wines=[('Nero d’Avola','Tinto · Sicilia 2023','Red · Sicilia 2023',5,18),('Pinot Grigio Rosato','Rosé · Vigneti delle Dolomiti 2024','Rosé · Vigneti delle Dolomiti 2024',5,20),('Falanghina','Branco · Benevento IGP 2025','White · Benevento IGP 2025',5,20),('Pinocchio','Vino Rosso d’Italia Piccini','Vino Rosso d’Italia Piccini',None,22),('Prosecco Bolla','Cuvée Première · Extra Dry','Cuvée Première · Extra Dry',None,25)]
ARROW='<svg aria-hidden="true" viewBox="0 0 20 20"><path d="M4 10h12m-5-5 5 5-5 5"/></svg>'
MAP='https://www.google.com/maps/search/?api=1&query=Foca+Foca+Largo+de+Jesus+1+Setubal'
INSTA='https://www.instagram.com/focafoca.focacceria/'
ORDER='https://www.ubereats.com/pt-en/store/foca-foca-focacceria-artigianale/lQHlMk2EQ-CRfwQZrfJmUQ'
for lang in ('pt','en'):
 def t(pt,en): return pt if lang=='pt' else en
 def price(n): return (f'{n:.2f}'.replace('.',',')+' €') if lang=='pt' else '€'+f'{n:.2f}'
 def btn(label,url,cl='button-dark',external=False):return f'<a class="button {cl}" href="{url}"'+(' target="_blank" rel="noopener noreferrer"' if external else '')+f'>{label}{ARROW}</a>'
 cats={'classics':t('Clássicas','Classics'),'signature':t('De autor','Signature'),'selection':t('Seleção','Selection')}
 cards=''
 for slug,name,p,cat,pt,en in dishes:
  cards+=f'<article class="dish" data-category="{cat}"><img src="./images/dish-{slug}.webp" alt="{E(name)} — {E(t(pt,en))}" loading="lazy" width="1000" height="750"><div class="dish-copy"><span class="dish-category">{cats[cat]}</span><div class="dish-title"><h3>{E(name)}</h3><span>{price(p)}</span></div><p>{t(pt,en)}</p></div></article>'
 other=''
 for pt,en,rows in extras:
  inner=''
  for a,b,p,c,d in rows:inner+=f'<div class="menu-row"><div><h4>{t(a,b)}</h4>'+ (f'<p>{t(c,d)}</p>' if c else '')+f'</div><span>{price(p)}</span></div>'
  other+=f'<details class="menu-details"><summary>{t(pt,en)}<span aria-hidden="true" class="plus"></span></summary><div class="details-body">{inner}</div></details>'
 wr=''.join(f'<tr><th scope="row">{name}<small>{t(pt,en)}</small></th><td>{price(g) if g else "—"}</td><td>{price(b)}</td></tr>' for name,pt,en,g,b in wines)
 other+=f'<details class="menu-details"><summary>{t("Vinhos italianos","Italian wines")}<span aria-hidden="true" class="plus"></span></summary><div class="details-body"><table class="wine-table"><thead><tr><th>{t("Vinho","Wine")}</th><th>{t("Copo","Glass")}</th><th>{t("Garrafa","Bottle")}</th></tr></thead><tbody>{wr}</tbody></table></div></details>'
 options=''.join(f'<option value="{i}"'+(' selected' if i==2 else '')+f'>{i}</option>' for i in range(1,13))
 html=f'''<!doctype html>
<html lang="{t('pt-PT','en')}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><meta name="theme-color" content="#21462f"><meta name="description" content="{t('Foca Foca em Setúbal: focaccias artesanais, carta e pedidos de reserva. Conceito MCC.','Foca Foca in Setúbal: artisan focaccias, menu and reservation requests. MCC concept.')}"><title>Foca Foca · {t('Carta e reservas','Menu & reservations')} · Setúbal</title>
<link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700&family=DM+Serif+Display:ital@0;1&family=Oswald:wght@500;600;700&display=swap" rel="stylesheet"><link rel="stylesheet" href="./style.css?v=clean-4"><link rel="alternate" hreflang="pt" href="./index.html"><link rel="alternate" hreflang="en" href="./en.html"></head>
<body id="top" data-lang="{lang}"><a class="skip-link" href="#conteudo">{t('Saltar para o conteúdo','Skip to content')}</a>
<div class="concept-bar"><span>MCC / WEBSITE CONCEPT</span><p>{t('Conceito independente — não é o site oficial','Independent concept — not the official website')}</p><a href="{INSTA}" target="_blank" rel="noopener noreferrer">Instagram {ARROW}</a></div>
<header class="site-header"><a class="wordmark" href="#top" aria-label="Foca Foca"><span>FOCA</span><span>FOCA</span></a>
<nav id="main-nav" class="main-nav" aria-label="{t('Navegação principal','Main navigation')}"><a href="#historia">{t('A nossa história','Our story')}</a><a href="#menu">{t('A carta','The menu')}</a><a href="#reservas">{t('Reservas','Reservations')}</a><a href="#visita">{t('Contactos','Contact')}</a></nav>
<div class="header-tools"><nav class="language-switch" aria-label="{t('Idioma','Language')}"><a href="./index.html" lang="pt" hreflang="pt" {'aria-current="page"' if lang=='pt' else ''}>PT</a><span aria-hidden="true">/</span><a href="./en.html" lang="en" hreflang="en" {'aria-current="page"' if lang=='en' else ''}>EN</a></nav><button class="menu-toggle" type="button" aria-expanded="false" aria-controls="main-nav"><span>Menu</span><i aria-hidden="true"></i></button></div></header>
<main id="conteudo">
<section class="hero" data-film aria-labelledby="hero-title"><div class="hero-image"></div><video class="hero-video" autoplay muted loop playsinline poster="./images/real-parma.webp" aria-label="{t('Focaccia da casa na esplanada','House focaccia on the terrace')}"><source src="https://d8j0ntlcm91z4.cloudfront.net/user_3IDQioFnKEdiBTSpvyKkSdi5fp9/hf_20260926_131535_f7e0cbc2-f493-4dc6-a73b-c8614eaf1826.mp4" type="video/mp4"></video><div class="hero-shade"></div><div class="hero-copy"><p class="kicker">Focacceria artigianale · Setúbal</p><h1 id="hero-title"><span>{t('A Itália','A little Italy')}</span><em>{t('entre duas fatias.','between two slices.')}</em></h1><div class="hero-actions">{btn(t('Descobrir a carta','Explore the menu'),'#menu','button-light')}{btn(t('Pedir uma reserva','Request a table'),'#reservas','button-outline')}</div></div><div class="hero-stamp" aria-hidden="true"><span>{t('Feita à mão','Handmade')}</span><strong>24H+</strong><span>{t('Fermentação','Fermentation')}</span></div></section>
<div class="ticker"><div class="ticker-track">{(' <i aria-hidden="true"></i> '.join(f'<span>{x}</span>' for x in t(['FARINHAS ITALIANAS','FERMENTAÇÃO LENTA','FEITA TODOS OS DIAS','SABOR ARTESANAL'],['ITALIAN FLOURS','SLOW FERMENTATION','MADE EVERY DAY','ARTISAN FLAVOUR']))+' <i aria-hidden="true"></i> ')*2}</div></div>
<section id="historia" class="story section-pad"><div class="story-heading"><p class="eyebrow">01 · {t('A história','Our story')}</p><h2>{t('Uma focacceria feita','A focacceria made')} <em>{t('a quatro mãos.','by two pairs of hands.')}</em></h2></div><div class="story-grid"><figure class="story-photo"><img src="./images/foca-02.webp" alt="{t('Focaccia na mesa da Foca Foca','Focaccia at Foca Foca')}" width="1200" height="1600" loading="lazy"><figcaption>Largo de Jesus · Setúbal</figcaption></figure><div class="story-copy"><p class="lead">{t('Gabriele traz a tradição italiana e quinze anos de experiência em padaria e pizzaria. Janainy junta-lhe a sensibilidade para receber e criar um lugar onde apetece ficar.','Gabriele brings Italian tradition and fifteen years of baking and pizza-making experience. Janainy adds her gift for hospitality and creating a place where you want to linger.')}</p><p>{t('Farinhas italianas 100% naturais, massa preparada diariamente e mais de 24 horas de fermentação. Enchidos e queijos escolhidos pela sua qualidade. Mais sabor, mais aroma, mais leveza.','100% natural Italian flours, dough prepared daily and more than 24 hours of slow fermentation. Cured meats and cheeses chosen for their quality. More flavour, more aroma, more lightness.')}</p><blockquote class="story-quote">{t('Uma pequena parte de Itália, agora no coração de Setúbal.','A little piece of Italy, now in the heart of Setúbal.')}</blockquote></div></div></section>
<section id="menu" class="menu-section section-pad"><div class="menu-heading"><div><p class="eyebrow">02 · {t('A carta','The menu')}</p><h2>Focaccia, <em>ma davvero.</em></h2></div><p>{t('Doze combinações. A mesma massa artesanal. Escolhe o teu próximo favorito.','Twelve combinations. The same artisan dough. Find your next favourite.')}</p></div>
<div class="menu-filters" role="group" aria-label="{t('Filtrar focaccias','Filter focaccias')}"><button type="button" data-filter="all" aria-pressed="true">{t('Todas','All')}</button>{''.join(f'<button type="button" data-filter="{k}" aria-pressed="false">{v}</button>' for k,v in cats.items())}</div><p class="sr-only" id="filter-status" aria-live="polite"></p><div class="dish-grid">{cards}</div><p class="menu-note">{t('Imagens ilustrativas criadas a partir do pão da casa e dos ingredientes da carta. A apresentação pode variar.','Illustrative images based on the house bread and menu ingredients. Presentation may vary.')}</p>
<div class="other-menu"><div class="other-menu-title"><p class="eyebrow">{t('E para acompanhar','And on the side')}</p><h3>{t('Do café','From coffee')} <em>{t('ao aperitivo.','to aperitivo.')}</em></h3></div><div>{other}</div></div>
<div class="menu-bottom"><p>{t('A tua mesa espera por uma boa conversa.','Good food. Even better company.')}</p>{btn(t('Encomendar no Uber Eats','Order on Uber Eats'),ORDER,external=True)}</div><p class="menu-note">{t('Preços em euros, com IVA incluído. Carta conforme as imagens fornecidas; preços e disponibilidade sujeitos a confirmação. Para alergénios e necessidades alimentares, fala com a equipa.','Prices in euros, VAT included. Menu transcribed from the supplied images; prices and availability subject to confirmation. Ask the team about allergens and dietary requirements.')}</p></section>
<section class="cutout-feature"><div><p class="eyebrow">BUON APPETITO</p><h2>{t('O protagonista?','The star?')}<em>{t('O sabor.','The flavour.')}</em></h2>{btn(t('Pedir uma mesa','Request a table'),'#reservas','button-light')}</div><img src="./images/cutout-spicy.webp" alt="{t('Focaccia sem fundo, em destaque','Focaccia cutout in the spotlight')}" width="1448" height="1086" loading="lazy"></section>
<section id="filme" class="assembly-section" aria-labelledby="assembly-title"><div class="assembly-heading"><p class="eyebrow">{t('O sabor ganha forma','Flavour takes shape')}</p><h2 id="assembly-title">{t('Camada a camada,','Layer by layer,')} <em>{t('chega a vontade.','worth the wait.')}</em></h2></div><div class="assembly-frame" data-film><video class="assembly-video" autoplay muted loop playsinline preload="metadata" poster="https://d2ol7oe51mr4n9.cloudfront.net/user_3IDQioFnKEdiBTSpvyKkSdi5fp9/3e324fbd-877e-491d-a67b-013a217c459a.png" aria-label="{t('Filme de montagem de uma focaccia','Focaccia assembly film')}"><source src="https://d8j0ntlcm91z4.cloudfront.net/user_3IDQioFnKEdiBTSpvyKkSdi5fp9/hf_20260926_105044_c00d2d5c-1c9a-4e76-9c4c-be86239b56c3.mp4" type="video/mp4"></video></div><p class="assembly-caption">{t('Filme de conceito · composição ilustrativa','Concept film · illustrative composition')}</p></section>
<section id="reservas" class="reservation section-pad"><div class="reservation-copy"><p class="eyebrow">03 · {t('À tua espera','See you at the table')}</p><h2>{t('Guardamos','Let’s find')}<em>{t('um lugar?','you a table.')}</em></h2><p>{t('Um almoço a dois, uma pausa com amigos ou uma ocasião especial. Prepara o teu pedido e envia-o à equipa.','Lunch for two, a catch-up with friends or a special occasion. Prepare your request and send it to the team.')}</p><p class="booking-note">{t('Este formulário prepara uma mensagem. A reserva só fica confirmada após resposta do restaurante. Para hoje, recomendamos ligar.','This form prepares a message. Your reservation is only confirmed after the restaurant replies. For today, we recommend calling.')}</p>{btn(t('Ligar para reservar','Call to reserve'),'tel:+351913602617')}<p class="small-print">{t('Hora local de Setúbal. A disponibilidade e os horários são confirmados pela equipa.','Setúbal local time. Availability and opening hours are confirmed by the team.')}</p></div>
<form id="reservation-form" class="reservation-form"><div class="form-grid"><label class="full">{t('Nome','Name')}<input name="name" autocomplete="name" required maxlength="80"></label><label>{t('Data','Date')}<input name="date" type="date" required></label><label>{t('Hora pretendida','Preferred time')}<input name="time" type="time" required></label><label>{t('Pessoas','Guests')}<select name="guests">{options}</select></label><label>{t('Telefone (opcional)','Phone (optional)')}<input name="phone" type="tel" autocomplete="tel" maxlength="30"></label><label class="full">{t('Mensagem (opcional)','Message (optional)')}<textarea name="notes" rows="3" maxlength="500"></textarea></label></div><button type="submit" class="button button-dark">{t('Preparar pedido de reserva','Prepare reservation request')}{ARROW}</button><p class="small-print">{t('Nada é enviado automaticamente. Revê a mensagem antes de a enviares.','Nothing is sent automatically. Review the message before sending it.')}</p><div id="reservation-result" hidden><h3 tabindex="-1">{t('O teu pedido está pronto','Your request is ready')}</h3><pre id="reservation-message"></pre><div class="reservation-actions"><a id="sms-link" class="button button-dark" href="sms:+351913602617">{t('Abrir mensagem SMS','Open SMS message')}{ARROW}</a><button id="copy-request" type="button" class="button button-outline-dark">{t('Copiar mensagem','Copy message')}</button></div><p id="copy-status" aria-live="polite"></p><p class="small-print">{t('No computador, podes copiar a mensagem e enviá-la pelo Instagram. O pedido só é enviado quando o confirmares na aplicação de mensagens.','On desktop, copy the message and send it via Instagram. The request is sent only when you confirm it in your messaging app.')} <a href="{INSTA}" target="_blank" rel="noopener noreferrer">Instagram</a></p></div></form></section>
<section id="visita" class="visit section-pad"><div class="visit-top"><p class="eyebrow">04 · {t('Visita-nos','Visit us')}</p><h2>Setúbal,<br><em>ci vediamo.</em></h2></div><div class="visit-grid"><div class="address-card"><p>{t('Onde estamos','Find us')}</p><address>Largo de Jesus, 1<br>Setúbal, Portugal</address>{btn(t('Abrir no mapa','Get directions'),MAP,'button-light',True)}</div><div class="contact-card"><p>{t('Fala connosco','Get in touch')}</p><a href="tel:+351913602617">+351 913 602 617</a><a href="{INSTA}" target="_blank" rel="noopener noreferrer">@focafoca.focacceria {ARROW}</a><a class="contact-sms" href="sms:+351913602617">{t('Enviar SMS','Send an SMS')} {ARROW}</a><small>{t('Consulta o Instagram para horários e novidades.','Check Instagram for opening hours and updates.')}</small></div></div><div class="visit-wordmark" aria-hidden="true">FOCA FOCA</div></section></main>
<footer class="site-footer"><p>{t('Conceito criado por MCC para Foca Foca.','Concept created by MCC for Foca Foca.')}</p><p>{t('Fotografias fornecidas, imagens ilustrativas e vídeos editados com IA. Conteúdo sujeito a confirmação pela equipa.','Supplied photographs, illustrative images and AI-edited videos. Content subject to confirmation by the team.')}</p><a href="#top">{t('Voltar ao topo','Back to top')}{ARROW}</a></footer><script src="./app.js?v=clean-4"></script></body></html>'''
 (root/('index.html' if lang=='pt' else 'en.html')).write_text(html)
print('Built PT and EN pages with 12 focaccias and full supplied drinks/pastries menu')
